stages:
   - documentation
   - quality
   - build
   - unit_test

variables:
  GIT_STRATEGY: clone
  TIMEOUT: 10m

docs:
   stage: documentation
   script:
      - make docs
   artifacts:
      paths:
         - docs/code/src

styleCheck:
   stage: quality
   script:
      - make style

staticAnalysis:
   stage: quality
   script:
      - make static

buildTests:
   stage: build
   script:
      - make test_project
   artifacts:
      paths:
         - test_project

unitTests:
   stage: unit_test
   script:
      - test_project
